import 'package:sexquare/screens/screens.dart';
import 'package:flutter/widgets.dart';

final Map<String, Widget Function(BuildContext)> appRoutes = {
  'cambio'                : (_) => const CambioScreen(),
  'conditions'            : (_) => const ServiceConditionScreen(),
  'detalleHabitacion'     : (_) => const DetalleHabitacionScreen(),
  'detalleHorario'        : (_) => const DetalleHorarioScreen(),
  'detalleInstalacion'    : (_) => const DetalleInstalacionScreen(),
  'detalleLocal'          : (_) => const DetalleLocalScreen(),
  'gps'                   : (_) => const GpsAccessScreen(),
  'habitacion'            : (_) => const HabitacionScreen(),
  'home'                  : (_) => const HomeScreen(),
  'horario'               : (_) => const HorarioScreen(),
  'instalacion'           : (_) => const InstalacionScreen(),
  'loadingAPP'            : (_) => const LoadingAPPScreen(),
  'loadingGPS'            : (_) => const LoadingGPSScreen(),
  'loadingLocation'       : (_) => const LoadingLocationScreen(),
  'loadingRegister'       : (_) => const LoadingRegisterScreen(),
  'local'                 : (_) => const LocalScreen(),
  'loginPhone'            : (_) => const LoginPhoneScreen(),
  'map'                   : (_) => const MapScreen(),
  'mapfull'               : (_) => const MapFullScreen(),
  'message'               : (_) => const MessageScreen(),
  'perfilUsr'             : (_) => const PerfilUsrScreen(),
  'politic'               : (_) => const PrivacyPolicyScreen(),
  'register'              : (_) => const RegisterScreen(),
  'reserva'               : (_) => const ReservaScreen(),
  'status'                : (_) => const StatusScreen(),
  'userFoto'              : (_) => const UserFotoScreen(),
  'users'                 : (_) => const UsersScreen(),
  'verification'          : (_) => const VerificationScreen(),
  'welcome'               : (_) => const WelcomeScreen(),
};
